# Generated by Django 5.1.6 on 2025-03-17 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rx_pending', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Production', 'In Production'), ('Awaiting Verification', 'Awaiting Verification'), ('Verified', 'Verified')], default='Pending', max_length=100),
        ),
        migrations.DeleteModel(
            name='QT',
        ),
    ]
