# Generated by Django 5.1.6 on 2025-03-11 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rx_pending', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('prescription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rx_pending.prescription')),
            ],
        ),
    ]
